# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import service_pb2


class StreamServiceBase(abc.ABC):

    @abc.abstractmethod
    async def TTS(self, stream: 'grpclib.server.Stream[service_pb2.TtsRequest, service_pb2.TtsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/streamservice.StreamService/TTS': grpclib.const.Handler(
                self.TTS,
                grpclib.const.Cardinality.UNARY_STREAM,
                service_pb2.TtsRequest,
                service_pb2.TtsResponse,
            ),
        }


class StreamServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.TTS = grpclib.client.UnaryStreamMethod(
            channel,
            '/streamservice.StreamService/TTS',
            service_pb2.TtsRequest,
            service_pb2.TtsResponse,
        )
