# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rstreamservice\"\xc0\x01\n\nTtsRequest\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06outfmt\x18\x03 \x01(\t\x12\x13\n\x0bvbr_quality\x18\x04 \x01(\x03\x12\x10\n\x08language\x18\x05 \x01(\t\x12\x0e\n\x06phrbrk\x18\x08 \x01(\x08\x12\x0f\n\x07speaker\x18\n \x01(\t\x12\r\n\x05speed\x18\x0c \x01(\x02\x12\x0c\n\x04gain\x18\x0e \x01(\x02\x12\r\n\x05token\x18\x17 \x01(\t\x12\x0b\n\x03uid\x18\x18 \x01(\t\"\x1b\n\x0bTtsResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32Q\n\rStreamService\x12@\n\x03TTS\x12\x19.streamservice.TtsRequest\x1a\x1a.streamservice.TtsResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=33
  _globals['_TTSREQUEST']._serialized_end=225
  _globals['_TTSRESPONSE']._serialized_start=227
  _globals['_TTSRESPONSE']._serialized_end=254
  _globals['_STREAMSERVICE']._serialized_start=256
  _globals['_STREAMSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
